### ISSUE TITLE
[ Question ] type폴더 관련 나눠보고 싶은 이야기가 있습니다

### ISSUE THREAD

**Issue by kiminn** [mobi-chap-chap/chap-chap#26]
type폴더를 저희 모두 의논해서 이렇게 진행하고 있었는데요,
<img width="421" alt="스크린샷 2024-01-26 오후 8 58 47" src="https://github.com/mobi-chap-chap/chap-chap/assets/134191815/1e49730a-2e98-47df-9eb5-478f533581ce">
이리 저리 찾아보다 보니 `📁type`폴더를 아예 `src`바로 하단 폴더로 빼서 모든 타입들을 담거나,
비슷한 것끼리 묶어서 export 하여 사용하기도 하더라구요!

src/type/common.ts
```ts
export type Cat = {
//중략
}

export type Dog = {
//중략
}

export type Fox = {
//중략
}
```

주석으로 달아서 구분한다면 이거도 꽤 괜찮은 방법인 거 같은데 단점이 있다면 오히려 너무 다 몰려있어서
'보기 불편하다 + 지금 있는 타입파일들 다시 또 바꿔줘야함!'의 불편함이 있을 거 같아요

근데 이런식으로 관리하는 방법도 있어서 한 번 얘기를 나누고 싶어서 이슈 생성합니다!
저는 빼는 게 깔끔하고 괜찮은 거 같은데 같은 의견이시면 진행하고 아니라면
이런 식으로도 관리 하는구나0_0 알고 기존꺼로 해도 무방할 거 같습니다

----
만약 진행하게 된다면, 
제꺼는 파일 옮길시 자동 import가 되니 마무리되는 거 까지 merge후에 
라이브 쉐어 켜고 같이 옮기고 확인해봐도 좋을 거 같습니다!

**Comment by 55555-Jyeon** [comment]
<br />

###  💡 Good Idea, Kimi 

<br />

저희 api 관리했던 것처럼 크게 나눠서 파일 분리해도 괜찮을 것 같아요 🤔

한 파일 안에서 나눠버리면 타입 길이에 따라 긴 것도 있어서 (특히 recipe)
type 폴더 안에 `user.type.ts`, `recipe.type.ts` 이렇게 나누는 것도 좋을 것 같습니다 :)
파일을 각 페이지별, api 종류별 나누는 건 어떤가요?

api의 경우는 recipe의 type이 좀 많이 길어서 분리하는게 좋을 것 같아요.
각 페이지는 props의 type 혹은 page 자체의 interface 두 개 정도인 것 같아서 묶어도 괜찮을 것 같습니다.

다만 걱정되는 부분은 저희가 ts.config.json 파일로 절대경로 설정을 하지 않아 
import 의 깊이가 많이 깊어질까 걱정되네요... 👉 `"../../../"`


폴더를 `src/type` 으로 생성해서 진행하게 될 경우 ts.config.json 설정도 같이 해주면 좋을 것 같아요! 

<br />


---

++ 
여담인데 저도 파일 위치 바꾸면 import 바꿔주더라구요...? 분명 안 됐는데 의식하고 보니 되는 기능이었습니다 👀
언제부터 됐던 거지..? Kimi 님의 쉐어는 대찬성 🙌🏻


+++ 
현재 파일에서 코드 추가로 진행하신 부분 있나요? 
경로 관련된 리팩터링은 나중에 merge할 때 충돌이 좀 걱정되네요.. 
내일 PR 각자 하고 나서 main pull 받은 뒤 같이 진행하는 건 어떠신가요??

**Comment by kiminn** [comment]
### 🐣 Good Reply, Amy

정말 큰 그림 잘 그리시네요!
좀 큰 단위로 연관성있는 것들끼리 묶으면 좋을 거 같아요 ㅎㅎ

++
여담) 잘 되신다니 축하입니다 🥳 짱편한데 말이죠!

++
네 저 조금 대공사 있..을 예정입니다
제발 충돌이 안나길 바라며......

각자 PR 후 내일 진행 동의합니다!

---

tsconfig관련 정리가 잘 되어있는 블로그 같아서 링크도 첨부합니다!
https://lasbe.tistory.com/151

**Comment by Ahnjuhyeon** [comment]
💡 Good Idea, Kim

맞아요 같은 생각을 하고있어서 고민하고 있었는데 좋은 의견같아요
타입을 하나 사용하기 위해서 각 페이지별로 타입 파일을 나눈다면 그것도 그것대로 비효율적이게 파일이 여러 생기지 않을까 생각했는데 

amy님 말씀대로 각 기능별로 나눠서 파일을 관리하면 더 좋겠네요!
import 의 깊이도 생각해서 ts.config.json 설정도 고민해야하긴하겠네요! 

저는 그래도 type을 나눠서 기능별로 나누는거 좋은 방법이라 생각합니다!! 

++ 
제공해주신 참조자료도 살펴봤는데 적용만 잘 된다면 매우 깔끔해 보이고 좋을것 같아요!! :)

**Comment by kiminn** [comment]
### 🐣 Good Reply, Ann

오 모두 같은 의견이시군요!!!
그렇다면 오늘 머지 후에 진행하는 거로 알고있겠습니다

아직 타입 스크립트 프로젝트가 처음이라서 좀 어질어질하네요 @.@
다음부터는 시작부터 이렇게 해야겠어용

++
좋습니다! :)
