### ISSUE TITLE
[2024-01-28] prettier 설정 후 오류

### ISSUE THREAD

**Issue by 55555-Jyeon** [mobi-chap-chap/chap-chap#38]
어제 prettier 설정된  main을 오늘 풀 받아서 진행 중인데 저장할 때마다 prettier가 적용되지 않고 있습니다..ㅎㅎ
`npm i` 다시 하고 코드 작성 중인데 안 되네요, 에러 있을 땐 잘 안 된 적도 있었는데 에러가 없어도 안 되고 있습니다.
설정한 사람 외 다른 분도 이런지 저만 이런 건지 확인하고 싶은데 잘 되시나요 🥹

<img width="1817"  src="https://github.com/mobi-chap-chap/chap-chap/assets/134191817/5a581bb1-7bc2-42fc-a8ab-825012309b64">

**Comment by 55555-Jyeon** [comment]
확장자 변경으로 해결했습니다 :)

**Comment by kiminn** [comment]
잘 된다니 다행입니다 확장자 변경 어떻게 하셔서 해결하셨나요!?
