### ISSUE TITLE
[2024.01.30] filter에서 searchParam 관련 질문 있습니다 

### ISSUE THREAD

**Issue by Ahnjuhyeon** [mobi-chap-chap/chap-chap#53]
제가 지금 진행하고 싶은게 밥, 국&찌개.. 등등 클릭하면 
해당데이터를 주소를 통해 받아오고싶은데요 
searchParam 사용해서 하고싶은데 생각보다 잘 진행되고 있지 않아요 
잘못된 부분이 있다면 좀 도움을 받고싶어서요!

<img width="583" alt="스크린샷 2024-01-31 00 02 02" src="https://github.com/mobi-chap-chap/chap-chap/assets/134281116/6c89b7e2-92d4-412a-b790-0456b12e2a37">

 이부분이 필터 페이지 부분이구요 

<img width="617" alt="스크린샷 2024-01-31 00 04 37" src="https://github.com/mobi-chap-chap/chap-chap/assets/134281116/5e686c7b-a65e-43c2-8f51-7def98d081de">
이 부분인 hook 데이터 받아오는 부분입니다 
어떻게 넘겨야 하는지 .. 감이 안옵니다아아

**Comment by kiminn** [comment]
혹시 압축파일 .env랑  nodemodules제외하고 보내주실 수 있나욤?? 
저도 열어서 확인해볼게요!

**Comment by 55555-Jyeon** [comment]
디테일 페이지에서 useParams 사용해 주소에 있는 RCP_NM 값을 가져오는 부분 구현되어 있습니다.

<img width="905"  src="https://github.com/mobi-chap-chap/chap-chap/assets/134191817/327fb4c1-8b86-468e-943b-29f21b629749">

이 부분이랑 api 부분 보시면 조금 도움이 되지 않을까 싶어요 :)

**Comment by Ahnjuhyeon** [comment]
결국.. 필터는~ 저멀리..
